apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD
    path: cp4ba-manifests/namespace
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogsource
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD 
    path: cp4ba-manifests/catalogsource
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmap
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD
    path: cp4ba-manifests/configmap
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD
    path: cp4ba-manifests/secrets
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operatorgroup
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD
    path: cp4ba-manifests/operatorgroup
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subscription
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD
    path: cp4ba-manifests/subscriptions
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4bacr
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD
    path: cp4ba-manifests/deployCR
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
