apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parentapplication
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cp4ba
  source:
    repoURL: https://github.com/lloydngcobo/CP4BA-with-ArgoCD 
    path: cp4ba-manifests/setup/childapplication
    targetRevision: 25.0.0
  destination:
    server: https://kubernetes.default.svc 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
