apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjcC5pY3IuaW8iOnsidXNlcm5hbWUiOiJjcCIsInBhc3N3b3JkIjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKSlFrMGdUV0Z5YTJWMGNHeGhZMlVpTENKcFlYUWlPakUzTkRJME5qUXlOemdzSW1wMGFTSTZJamRtTm1Jd1pEUXlaRFpqTXpRek9UQmhNV05oWWpNMlpHVXdOalZsWldNMkluMC5KOU1yLXZmaWVQMnkxSzN5TWluMHF2OThrUXVpTkZidnFKMGpLTDU3Wm4wIiwiZW1haWwiOiJ5b3VAZXhhbXBsZS5jb20iLCJhdXRoIjoiWTNBNlpYbEtNR1ZZUVdsUGFVcExWakZSYVV4RFNtaGlSMk5wVDJsS1NWVjZTVEZPYVVvNUxtVjVTbkJqTTAxcFQybEtTbEZyTUdkVVYwWjVZVEpXTUdOSGVHaFpNbFZwVEVOS2NGbFlVV2xQYWtVelRrUkpNRTVxVVhsT2VtZHpTVzF3TUdGVFNUWkphbVJ0VG0xSmQxcEVVWGxhUkZwcVRYcFJlazlVUW1oTlYwNW9XV3BOTWxwSFZYZE9hbFpzV2xkTk1rbHVNQzVLT1UxeUxYWm1hV1ZRTW5reFN6TjVUV2x1TUhGMk9UaHJVWFZwVGtaaWRuRktNR3BMVERVM1dtNHcifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4ba-project
type: kubernetes.io/dockerconfigjson
