apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: cp4ba-project
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE3NDI0NjQyNzgsImp0aSI6IjdmNmIwZDQyZDZjMzQzOTBhMWNhYjM2ZGUwNjVlZWM2In0.J9Mr-vfieP2y1K3yMin0qv98kQuiNFbvqJ0jKL57Zn0

