apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: cp4ba-project
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICAgImNwLmljci5pbyI6IHsKICAgICAgICAgICJ1c2VybmFtZSI6ICJjcCIsCiAgICAgICAgICAicGFzc3dvcmQiOiAiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUpKUWswZ1RXRnlhMlYwY0d4aFkyVWlMQ0pwWVhRaU9qRTFPVFkyTWpVMU1qUXNJbXAwYVNJNkltRXhaVFV6TXpZek5HUXlZelJrTjJZNU1qY3dObVpoWmpsalpUZGlNVEEzSW4wLnVGVm5CaWw2SFlrLUlyUUhrMGFHVXI3REtSNng2bkVEdUtxM3VlSXRpbXciLAogICAgICAgICAgImVtYWlsIjogIiIsCiAgICAgICAgICAiYXV0aCI6ICIiCiAgICAgIH0KICB9Cn0=[root@host-rycvrvrw9r20la80 cp4ba]#
type: kubernetes.io/dockerconfigjson
