apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp4a-operator
  namespace: cp4ba-project
spec:
  channel: v25.0
  name: ibm-cp4a-operator
  source: ibm-cp4a-operator-catalog
  sourceNamespace: cp4ba-project
  installPlanApproval: Automatic

